import{a as w,S as v,i as l}from"./assets/vendor-BfjKTZs6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="49577891-dd8edba8495efad2486051016",E="https://pixabay.com/api/";async function g(o,t=1,s=15){return(await w.get(E,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}})).data}const f=document.querySelector(".gallery");let P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function R(){f.innerHTML=""}function m(o,t=!1){const s=o.map(({webformatURL:n,largeImageURL:e,tags:r,likes:a,views:b,comments:L,downloads:S})=>`
        <a href="${e}" class="gallery-item">
            <img src="${n}" alt="${r}" />
            <div class="info">
                <p><b>Likes:</b> ${a}</p>
                <p><b>Views:</b> ${b}</p>
                <p><b>Comments:</b> ${L}</p>
                <p><b>Downloads:</b> ${S}</p>
            </div>
        </a>
    `).join("");t?f.innerHTML+=s:f.innerHTML=s,h()}function h(){P.refresh()}const T=document.querySelector(".form"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");let c="",i=1;const p=15;let y=0;T.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),i=1,!c){l.warning({message:"Please enter a search query.",position:"topRight"});return}R(),u.hidden=!0,d.style.display="block";try{const t=await g(c,i,p);y=t.totalHits,t.hits.length===0?l.error({message:"Sorry, no images found. Try another search!",position:"topRight"}):(m(t.hits),h(),i*p<y&&(u.hidden=!1))}catch{l.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{d.style.display="none"}});u.addEventListener("click",async()=>{i+=1,d.style.display="block";try{const o=await g(c,i,p);m(o.hits,!0),h(),$(),i*p>=y&&(u.hidden=!0,l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{d.style.display="none"}});function $(){var s;const t=((s=document.querySelector(".gallery").firstElementChild)==null?void 0:s.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
