import{a as S,S as u,i as s}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="49577891-dd8edba8495efad2486051016",v="https://pixabay.com/api/";async function p(t,r=1){const a=await S.get(v,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return{images:a.data.hits,total:a.data.totalHits}}const f=document.querySelector(".gallery"),g=document.querySelector(".load-more");let $=new u(".gallery a",{captionsData:"alt",captionDelay:250});function B(){f.innerHTML=""}function y(t){const r=t.map(({webformatURL:a,largeImageURL:l,tags:e,likes:o,views:n,comments:L,downloads:w})=>`
        <a href="${l}" class="gallery-item">
            <img src="${a}" alt="${e}" />
            <div class="info">
                <p><b>Likes: </b> ${o}</p>
                <p><b>Views: </b> ${n}</p>
                <p><b>Comments: </b> ${L}</p>
                <p><b>Downloads: </b> ${w}</p>
            </div>
        </a>
    `).join("");f.insertAdjacentHTML("beforeend",r),$.refresh()}function M(){g.style.display="block"}function P(){g.style.display="none"}const E=document.querySelector(".form"),d=document.querySelector(".loader"),R=document.querySelector(".load-more"),m=new u(".gallery a",{captionsData:"alt",captionDelay:250});let c="",i=1,h=0;E.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements["search-text"].value.trim(),!c){s.warning({message:"Please enter a search query.",position:"topRight"});return}B(),d.style.display="block",i=1;try{const{images:r,total:a}=await p(c,i);h=a,r.length===0?s.error({message:"Sorry, no images found. Try another search!",position:"topRight"}):(y(r),m.refresh(),b(r.length))}catch{s.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{d.style.display="none"}});R.addEventListener("click",async()=>{i+=1;try{const{images:t}=await p(c,i);y(t),m.refresh(),b(t.length),x()}catch{s.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}});function b(t){t<15||i*15>=h?(P(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M()}function x(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
